#ifndef OTHER_FILE_ALSO_INCLUDING_HEADER_GUARDED_FILE_H
#define OTHER_FILE_ALSO_INCLUDING_HEADER_GUARDED_FILE_H

#include "HeaderGuardedFile.h"

#endif // !OTHER_FILE_ALSO_INCLUDING_HEADER_GUARDED_FILE_H
